### ISSUE TITLE
MongoDB Atlas database/details missing

### ISSUE THREAD

**Issue by tejasrajanna** [anijitsahu/react-app-simple-music-app#2]

**Comment by csaluns5** [comment]
@anijitsahu Awesome job, thanks for making it public.
I am facing an issue, could you please help me resolve it? Details are given below.

Connection to database is failing with timeout. Please find below the screenshot for your reference.
It would be great if you export the database and put it inside project so that people can create their own instance instead of using you account?
Alternatively, if you can help to create the local database that would be great.!!

![image](https://user-images.githubusercontent.com/73182710/103786971-0c1acf00-5063-11eb-8cd3-eafcd1cb1a06.png)

**Comment by csaluns5** [comment]
@anijitsahu Can you please help us solve this issue?

**Comment by csaluns5** [comment]
It might be because the connection url you have set in the code belongs to the old version of Node. It would be appreciated if you can add url for all of the Node versions available in your connection settings in Atlas Mongo.

BTW, I somehow managed to get to it by doing some wort of guess work.
Here is how your database should look like.
![image](https://user-images.githubusercontent.com/73182710/103909781-194ec100-512a-11eb-9e04-01130f8d5d02.png)
Please ignore sample databases and collections.

Someone can create their own accont and an instance of database/collection and use it. If you get the above mentioned error here are few links to help you solve them.

https://stackoverflow.com/questions/61800062/error-querytxt-etimeout-when-connecting-to-mongodb-atlas-using-mongoose
https://stackoverflow.com/questions/52632830/can-not-connect-to-the-databasemongoparseerror-unescaped-at-sign-in-authority-s

I hope, it will save life of people.
